include("${CMAKE_CURRENT_LIST_DIR}/biuTargets.cmake")
find_package(magic_enum REQUIRED)
find_package(fmt REQUIRED)
find_package(Boost REQUIRED COMPONENTS headers iostreams filesystem process)
find_package(range-v3 REQUIRED)
find_path(NAMEOF_INCLUDE_DIR nameof.hpp REQUIRED)
find_path(ZPP_BITS_INCLUDE_DIR zpp_bits.h REQUIRED)
find_package(concurrencpp REQUIRED)
find_path(POCKETFFT_INCLUDE_DIR pocketfft.h REQUIRED)
find_package(yaml-cpp REQUIRED)
if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
  find_package(Eigen3 REQUIRED)
  find_package(HighFive REQUIRED)
  find_package(TgBot REQUIRED)
  find_package(HDF5 REQUIRED)
  find_package(cpptrace REQUIRED)
endif()
