users:
    #ENC[AES256_GCM,data:2KeaiyOl51RB,iv:BGqlx1jzOWgG1zaxGfDtWfpbrgFCgAiTbPPMHoRP6KM=,tag:VhbvcwxV561iB03zIhvPQg==,type:comment]
    xll: ENC[AES256_GCM,data:Y9jk/9yKwYiUeC9h7NkNNRYllyakXco108J8ZPLYQT+u7NsIMZ4kw27IjV4ytwH3k5Xid4jLKEsmKayNAW7kPNdbFfACcugL7w==,iv:cDtPmsHefigsqJZMPqOReVj9YOOgDXQhmulUHYUqYfo=,tag:8SS8dstzuon6f3y4pVA+wQ==,type:str]
    #ENC[AES256_GCM,data:fptM8gt/IHBZ,iv:gX09x6/ZRXIXG0wOFBUCj6ZtMaTXebcSzvFMsS8vxcY=,tag:M5KFPF8Gmsd87lQ/hqhXnA==,type:comment]
    zem: ENC[AES256_GCM,data:w0797tV3yFqXbZmhB48kvxK1SJCAFpIjgja2sai2YQB2Z3ELJaQMTIsmgI6p85m/Q15nzFVPdEAsxz6ts3eskRttOSw9mXeNyA==,iv:D3yesKHqbhab1Zk5ZKAm9sKi5KXVt+0JD0pOO5VgptY=,tag:ySURHTqQc0Rxd2u1igZ8Kg==,type:str]
    #ENC[AES256_GCM,data:XwSZ0w8UgIgR,iv:i4tBBEC/lagRmk7AbzFFjDEnKOzxObkTul/wc+tyyXA=,tag:EKrU4YZ4iOaXpbn/lrZJlw==,type:comment]
    yjq: ENC[AES256_GCM,data:Oy6b2sl59z2WA5/ifzJoq1KHzvbo+Izwac7yInRPGURxymUU/KvwW8p/XXIJsKkd2BjNaYkdELjNVrhTFd/tRhK+mCy8GSK4Lg==,iv:AGVSFIyqI5HNA+5e+ME3FKKoYMS4MCi4gjaxknord1A=,tag:ayLj6n98F2r62WdDqIaE3w==,type:str]
    #ENC[AES256_GCM,data:H1WyypgcuhcF,iv:mw2bcXzisgxeUIw6zC4nwHPhsrz5XNIsL72aGyEwyX0=,tag:A2Cb+DuX0BM61TK6/nWEgw==,type:comment]
    gb: ENC[AES256_GCM,data:ZfcJtiEmdZux90Vqn/L8oq16C10rfRPhxX+FnskJ/+OfdAVheEt9IeIdXpkVfIXU68rIBhDFI60Andm9gmddqoQqHhBj/W9gAA==,iv:fyCkc92YxeIumHODfOU2PWpVfeDJ8RKxKHRfFUYGF0g=,tag:cIn5rZSN8fONNz2GNSUOow==,type:str]
    #ENC[AES256_GCM,data:5q0u/KpWah5X,iv:FiMDektaHAFHenCT89skQ7gQgoMHdY8BtoyEv0L3npA=,tag:tNtRbpY2bYIUVjLx+IwGvg==,type:comment]
    wp: ENC[AES256_GCM,data:EcAOCjsqNFzRQtgjgtLn4X7G05cTN/SCmEGCtV/DRISj20Y3kMzbOSmtJoeII7mVA1WITxjhyBXX7abFjD80sZMGF4Th87kXiA==,iv:er9mbrz3F81vHLGPNYiyVO80hOXI3ZjFUuJbMaYWNeE=,tag:le7Fw45V0pdkHoXywdjFsA==,type:str]
    #ENC[AES256_GCM,data:bh0mHOovPAba,iv:doFuGvLagS17tgNm28J+T1qTvXAzPsenVN3heTDkNts=,tag:e0lsqlvXVk6lDqe1xGkemQ==,type:comment]
    hjp: ENC[AES256_GCM,data:agAmi5i8cdAC5B75E92PbDGG399AJyI87zbgErtYxM5CHLTBxPjAfqLLEAHTdRbfo53wHQEbG4/fFkunwrHrCdspKtsuFrK4xg==,iv:m+MregSzL5EsuNW/oiJXJIFeq4n1CAaQQV9AKId7rxg=,tag:nOI//Z/4gBfB7F2jwX7cWA==,type:str]
    #ENC[AES256_GCM,data:jHalo04u3gd+,iv:RjIwI0Kqmy0uVTxRRu1gNG/2eZXnl7iiuC9KOSV1RfU=,tag:Jvza//JVEtLwdtYk5+sY+Q==,type:comment]
    lly: ENC[AES256_GCM,data:5ZHy3nXe4SoGi+hu+woQwB/h7HyLdDlE6fkO6FXttEW4ZaBjIqiXOz2M9XMTmcMih9S7fGJPXDBD76oHGVY5W5ytyi3i1wyaFg==,iv:RWhQFYAIs5AELumViQRTsVPNfsV59zQYDFVX+DZpPrc=,tag:R3E1IBUAN7XOjrwNEwjZ5A==,type:str]
    #ENC[AES256_GCM,data:fz4CpQWCXmHX,iv:8UexUxCvtcmk7S8qPdKd3jxro7PspCYX6G7ujAEQ7HM=,tag:LgyieyMQ0zZLD0EW+POeoQ==,type:comment]
    GROUPIII-1: ENC[AES256_GCM,data:WfdbkyWIDl+lD3xPC5TMBQ+U2hIjHYyhNhnZ1PH9uowSdRCqoPAJ2GS7X35WrlrgTl67ByaTwhXP8r9LR7eL0YwdivTL/wxOXw==,iv:OBaEPQVBeShs+UH2BBIBLGT44tPiVyQ8G1ReZ4jALH0=,tag:SnwGrb3eI57rJUoqE6HR0g==,type:str]
    #ENC[AES256_GCM,data:OWTTbVhXIxSp,iv:GP6a2S9XdQ0xzTBQ91zkEgrNMtY1WVodTH/F/wh/mqU=,tag:6nzpvk9RFsAJxaL0Qiau0A==,type:comment]
    GROUPIII-2: ENC[AES256_GCM,data:NMnWdKTGyK9AhrmzdDaxgzeFbbc0TGPlfYzOr7g0zexxBTjyJiwox9thEglkkyA23e5GgNs6zObqUknZT3M7/epzbQDoSQYCmQ==,iv:+nSj1P2LlME48VjSF1t2ziPkhgKiDlLkAaL+PBCV/hU=,tag:41YqBFHAbfrmbf3kVC45CQ==,type:str]
    #ENC[AES256_GCM,data:0QMjEtxrhSj8,iv:YyMHdZTx/OViWBZ+1CGGAwaOLlqR6WdrKG1g44sZGYE=,tag:N5uMwbWJJF+DGiopdYm2Mw==,type:comment]
    GROUPIII-3: ENC[AES256_GCM,data:c+HRdDZPugIVI2vmuOlorhjZzxS11c6CJiZ3ZEwFFHfIoIUmGsXoRPGraJ0BjI3W+XZbI6qk211yufTgXLVj7nOVi0PW/9mteg==,iv:H8DlkTjkL/f6Oa2LG3dHRsJuWkEqokUJ/mjMyDnEAc4=,tag:0QmUyfAbYnn7vs4AdwQtYw==,type:str]
telegram:
    token: ENC[AES256_GCM,data:zfMATU2E6cwoiyfszV35vkQG6JSk00y589wmGEf4wQNncPhNsvh+NcSfnTwHTQ==,iv:Q46mUquhUZLGQsCDYitk4IPu24MpVnYmi7aHyZL/b1E=,tag:QVbrwAA9mWK/ToJfGIs9ug==,type:str]
    user:
        chn: ENC[AES256_GCM,data:mTt2D+SkvVL8,iv:L0Pk5p46E2kKBdRWCGpwOKS0BsbIhZUslpIFWvkssMY=,tag:+AjbNJ1SW/8Mx1HLpWAd2w==,type:str]
        hjp: ENC[AES256_GCM,data:ZXTQhax0gT4PKw==,iv:MerbaWWC4SLazEuuJrxAxf9e5aaX9xpq9St+h9aqvMQ=,tag:x9knShK90OKZPcn9fKzvMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19ax6vm3pv8rph5tq3mmehd9sy9jk823tw8svsd790r0lkslycquqvlwz9m
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUMTExdGd6dXhEWmxwWG8r
            NnhUNnB3amF6NWdwOFozR2lWQ2d0UmRNNEE4Ck9jV21WRHEzcWorc2RxYVZ2RnA2
            LzRVWEhRWi9IaWpxQkVQYlh6VlJVUGcKLS0tIFBXajBVSkVDYkI3b2k2L29WOERC
            RE0xSFNDMS9UaFRoNTVJVHY1dzh2WjgKq0o+nHzvV30kV8XavY3Ykxh12ls9q2+3
            HJBFRT76n94OkDPw4GOP1CcKfLPL0L5pKmL6RA8Sl5oxYW3baLN5bg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ffvr5pqd2lfj24e3fh53s92z6h76fda3du4y4k6r3yjumdwvpfgqzj033a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRVkxOFo4eUd5Q0I3NDRE
            K01qMEpYTG45a3IvOCsvSlZneXl6K1lILzBzCitzeTVVNHhFWHA1L0hWdHU0b1RG
            dDJOWk5NZlcybzRhMGZGODJuOXRqcFEKLS0tIDFiV0tNY3U3N0xJSjJ5NUYvOFFL
            Z21yY21NckNYVm5rOGxjTnRNNHphNHMKeiVE+YFZLMFhlZ4Sf+XH/CDaudH+UZ7j
            K0jUHrzwLb/0qALCFrXZa8a3e40NihhQQsHSpI8BgOfHYEFTRVqRjA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age164tyqklwhdm57tfm5u863mdt2xrzrrzac4py8a0j9y6kzqcjy9zsp073t6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjN3lVWm9sNDE0MnMySU5q
            MGFiN3ltdGt5V2h2azcrZE41SWRtTFQ0NWtFCktBc1VjYlMwdURNUEdScnlodWUv
            NGRFVERzNzY5cHR3eUR1MmtoYTNxcVkKLS0tIGlVOEZjVUp4ZCtTSGIyNWdCYkdR
            QVVJc2IyMnUremFmT1pMbGlZWDRmQ2cK8oAOfF9DpC+Xk9M0FXqW5FRHWnwZW1Cs
            qZMcv8j9poodoPWCP8hNzyFyK7Kv3BE9bErTm2ImSrW4Ek4PY/pMig==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age137x7csalutwvfygvvzpemlsywvdxj3j4z93a50z2sjx03w6zau8q3r5902
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5S29WMzhRT21WaitIdXJz
            N2RZSy9GV1ptcGg3L00yQ2N4eGMzNVdkSm5VCmhqZzRQNXZ4aVZ1WW54clJvQWVO
            MTVrbHRpK3pZT21LUWxPQ2JPRDMwUTQKLS0tIHVOMjJnamtZMFgzSVhXOWc4amZV
            ZHJnZHMvQ3RPbzR3ZTZCY0xiN3JnbmcKf7PV5P3mfUOWW2Zj0hMs4MILLHDGya2x
            cbnhFgAQv3CSTB+m9SEr1QHDKZ3mOaO+Uljd6TsqCR9sx9Je+4IEUg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nzetyehldf3gl6pr6mu5d2cv387p8wjqn6wfpll7a3sl8us6n38s0ds633
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3bW9mWnR4UHJ5ZmU1UVlT
            Z2xZdjVLOU02QUE2ajI5T25idElSenJ1ajA0CllWNEI1TGFpS1p0THBOKzB2MnVY
            bFJrVkJnMWtHWlpxSVVUcmNUT1kzd3cKLS0tICtnTW82R3MraXUxUFA2ZkxnbzM3
            U3Q0elJBbWY0cXFRQm4yYzFPMmRqaHMKffEaB0A3zV3PVf8xp/dOqyenVyvGMgbl
            76p5Sh2qvmp/S3jUiO29ti8YJHNGhG/ZBA0LmTcdboyBPMfLw1CVuw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1wj33xt8nj7rhnsenepsf6k3lmq5vk4wn84jwr55qy9cwu05xn5cspg3h7t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3bFhqM1F5OTNnRk5FZTNu
            SGV5NTJXQzdqRm1ucGt0TmcybGROSCtESEdvCm5lcExoQzNmSWxSSXVyOWQ4dVE4
            MlUrd2t6bFdIUm5hVzE2ZStrUjBKcE0KLS0tIDYzVE1IMEtLVkxIeUZFSG5zMyt6
            NVVtZVV4cjl5Z2dpbHZIemxaMEF0T1kKPDA6Nd6AMW2zWgdBl58c4FmdHXAOI5hy
            Cehl/KgssLXIYEAMLsQ7Lwf/WbR4CfNh/gSkuqLHtYYGnXmteR1I9g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16e7ykphshal6qhwfvat698hl48s8yr0jvzh27ecdyfh5uk7t9u6s753jgy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBURkF5Sm56Unl0WlJRUHQy
            SWxjSzRheTJVUVFhSUFLTVJlSFkwaTB1MkI0Cklvdk9rTHZuMzdpdVVWV2ZSZEh4
            djgwT1RzT3V3ZFBDSGNZVVRMbkQ1UFEKLS0tIDF5WDYrSGNoZklESmJpRzhtekNH
            UjJsZnMrcUI4UklDRzhEV3BvaHVRSW8KTARhRf9xmbI1AoME5l96I8o4DyfOuyw6
            8VI1uVJlw6yNKq8MzUIKE/NydpDypcQYELjHrKjhjk9rT3HzBaPlKw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1l4stuz0vr7gs7pqwjrmezam44702jp2vmqaqyxw0l0r42kf9updq4dfhrw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEcmV6U0J5Vy9ZRFhncXdJ
            cWpNVWFZN0FYOWMyY21obUdta0crR2hvY3owCkxSS2lJNVlibXlTVmh6NmZDc0I1
            TjlSYnJuVERlL3lZNU9vSVdiSk1iL2sKLS0tIDVpcStHQzlaRkZBWGZMd0piQU04
            RUp4OWY0djZWK29NN01pTnYyZFN1eVEK0x9exfANrudQljGxI6QNwoSpOaBJxZ7C
            y15p6PAhfZpik3iSRGVM+frTViFqZ+es1i4QDAY8BSMJZ9YGvKLxMw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hnarptkze0ujpp05dqr8uma04cxg9zqcx68qgpks5uf5l6rpk5gqhh8wxg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDWjJTRllJSnhvUENmNVhu
            NFMrdW9uS1IwaUVmdUUxcmxPb3VRQ2ZHbFY4CnowLzFRODR1UUFiK1B6WVRyZ29L
            MTN6RjdKbll6YWlrZGRkN2FxQ1F0U00KLS0tIEFZbGljZ2FLcm0ra2pEcCtCYXh2
            d3FrV3pmbUk1UVg0REo4WUduWGwvVVUK/NvlbJKUS9bMdj+H6HpKTLyVuCdRaclo
            DRqqS2eMnPkWvHuRrJX7B1m14MGi1lDqZIuOjMPcsEYem5kK0nOGrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-07T05:58:09Z"
    mac: ENC[AES256_GCM,data:czE8TzJ/wtWFIv5WyM/dR/SbZTvPkwA83o5y2+AIfuWXwyX65VuX1TkrQ6GUR8is22p3cdFgxtdAJmjgOK0tuD8u6Ek3WirwO+YwI/mm3UX9kxnPmZb2QcQsrRgBVMMeu/Loc7SI+XzhBLSX3ZdnugSMoZWe4ydbemPPfOlV+2A=,iv:/VTMsIm3umCjI8o3H7Xk0WM0vMt+Y/uFcW8LLDBEdqM=,tag:5H1FoPbSKgv8f4tV0esANw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
