slurm:
    munge: ENC[AES256_GCM,data:SbgMp7ofXOuoctXp9nSmd432KqdAyrKist8I7BimXDZXlnR/vfIfyQVFF2uXM/i8SQmTBN4gcgw2BNehChCrCbbeGo+742F804R1oVZHI3a48GXfaqMx0wH2VDoy7ez9LmjJYrUEFQE7r9AB5RCrtNSuBveT+tqXA51Z7CGdZBI=,iv:LSU+pIMdovVInyIiE+q+jgbfqJ7lPWvbMc7wsCidKQY=,tag:JswO9Qwuhdg95rt77bE3qA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IGFUbWd4ZyBBcWtxQkFh
            REZuR1BOdENJR0V1SlB5TUZqdHBJWWRPMmg4QlJxY2ZsdW1MQgpLRlRUeWdhY2lm
            NSt3L2M3NVZTb1V2ZUZIUW54Q2tnVWdHTTNldVpCdmdVCi0tLSA2TWl2ZlFUQlhX
            U2lEV1I2MFoxRm4waTZBaDlDYlk5bUFJWWZwSnJmWnVnCnraT7UmWQ+s4fgZb7S8
            v9b7eIPRIQwS03ZICRIZ0Q+wjKkDXRs05j0C/sVGI0CbmI2/M+5+tj/N8cjbtFkQ
            5vQ=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qtkjcn7umxt8j9zvrmnu7r6rgvl69c2u2zv8ufut4de2ealk2axvj9k0f03
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBraUpyTlZ6SXk4d0FreUI4
            Mk05UHExZW9UbTFlTGNjVkwvakE5RDl2V3lBCjlZenh5RlA2N3J3SHB2NVovOWVv
            enllcHRIQ0lkMU9pL09IN2R2STQrcVkKLS0tIENOcnZ0bnJTYkh6aWs4NXRLT2o1
            QmJYZ0tZOVIySzZpalR5V2QzbHYyUmcKa3pTUlmyDu4qhmwEUXRjczp8nEDmP6Dc
            rQbc2VgIHJnwzOmjOMfPAMDg4Yk0IY5YfIaWbsn1rqOZJCoAGmyp7A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hnarptkze0ujpp05dqr8uma04cxg9zqcx68qgpks5uf5l6rpk5gqhh8wxg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiSU9MdmJlZHFxQUhWL1l6
            ZEdWWUtPRnh3TWUrL1JqUGpXSlpSQUg0eEJVCmx2RU9scUtyclo4K3hHaVNWYWI0
            NlljZktKQjZuK0RlYVIxVytuc2VOWUkKLS0tIHlCMks2T3F5OEdkZFVLaWw5bXNB
            dFN0V3BPbGQwNWlOeWY1NDkxWXRaNEkKYsT63/W7RQkHZ1dE3vcac54NzUhyxe+b
            0mbMk+cj4ChIc3QxjszRUp5Q/XsCanSCLfMYT2nebVCnZnBXEzpUaw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l4stuz0vr7gs7pqwjrmezam44702jp2vmqaqyxw0l0r42kf9updq4dfhrw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0RW1CZHRBcHk5c0ZvY2tO
            bEM5VFREZGh1ZzVpT2xSTlVPL3ltdDdTOEJNCnBudEo4ZzlmUW9qM2VjQUQ2N2I4
            bWVhWkZwZzlkUVZoZWdHQXNCQTBUWHcKLS0tIE42U0Nod1JuclZwVlNvTktLazJo
            bklJUSsyVmhzY1pRUlpPNkFSdktYNUkKsMpOIlSdfz8j40D3v/eOQQRQt+gJEAA8
            sf8kMu7UQjWlkenw/IXDnICMzoQo96CLrrHkAnCMvYTy4TlVLfz7aQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k2y0vm4tmf88vg6zfed8q8zv544g4u0l5ry4kmm4hmzslvj5vdxskhat2n
    lastmodified: "2026-05-12T12:22:48Z"
    mac: ENC[AES256_GCM,data:Jc2aclU3Q9M7rsIO/Ww9R+YlX8+c3Xvhe2wKGl8o+O9TwL+MUW7h2Vk968RBBmktRCz62RopF4d36QZK8uQIc8kYdXuQn+papxejxp7N7rTSNVGovNCI9RCSwg0R3MEoEpQQkm8NPyI+apSVX+2H0Qx8tQuxPKWSBuvpaijOQlE=,iv:D+3xvpnhclcEV0FWhnZ9dqkXazh2BqYbornzpumeOyI=,tag:Ex68R7pqSjTDVj/z7p+OyA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
