slurm:
    munge: ENC[AES256_GCM,data:SbgMp7ofXOuoctXp9nSmd432KqdAyrKist8I7BimXDZXlnR/vfIfyQVFF2uXM/i8SQmTBN4gcgw2BNehChCrCbbeGo+742F804R1oVZHI3a48GXfaqMx0wH2VDoy7ez9LmjJYrUEFQE7r9AB5RCrtNSuBveT+tqXA51Z7CGdZBI=,iv:LSU+pIMdovVInyIiE+q+jgbfqJ7lPWvbMc7wsCidKQY=,tag:JswO9Qwuhdg95rt77bE3qA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IE1wVWkzZyBBcmo3c3VJ
            cmpsS1hLaE5EeDZ3TUtXT2xPS2d5TEV5eENLYktrTFhiWVZaSgpVNzZlRzRXVUx0
            b2pRaUxYYlRNVnhmVzllNmtMSnRxWWtuU2ZmVHArSCtzCi0tLSBjSTJaaUVQcmky
            RDkrR25QWEUwL0ZSemtQMWVPNTd3cm42dzJjZXdTMkg4CmQuwk/JgdYgOeRFt3/m
            dEQR0VJg2nW56r1jLe1j14E1HIZOrMbLAU27U53wv0bZW+kXdMWJi12cx8vhmWoQ
            Jns=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qvkn6rxkuh38fdrz6rqusz49lxhj500cmyac26v7dsr08rvskp78kv8uu69
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3enh5dlZ1OGhjejZ2djZC
            bkp4L2RHTURTNmRhVDYzM0UrbGtvMzJKL3c4CjltR01vM3ZKMTZBaXl3cXBtOW5Y
            Ym54cHprZWp6dGRrUVFNT1kyUC95dVUKLS0tIEd5cUZ0ZE5US0c1SEZoUHJOSENG
            enlwMmR6M2JlYWtsc2p1V0VmejJJUlkKk1YhZzEwPNj6bdZShvaCvqSkRSFY5tC+
            sMoLFhNoU/+HWbamYmJQ3xltRufkwJ2lkZgUAFaFiBQY82rRpu3hpg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1hnarptkze0ujpp05dqr8uma04cxg9zqcx68qgpks5uf5l6rpk5gqhh8wxg
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQSUp3VG1xdVdKWmllZUlx
            Q3QwTHM2bWRpZEpVRlRENGh1M0tFYUNYQUhBCjhpcWxWYWp2OTdVVndVYktLd044
            aGpRNElNajhTY1JqTkt1cTVVOGlqUTQKLS0tIG9Ta1hrUFB1aFdLVTdtRkhkUzFa
            QnBoUWF1UEJiSG9xaDlBeGJWa09xSVEKl9yfc0OO2uEjd6y2AY0nY/Hk1ylebt/q
            i5cE75xigvFi3VYXd2VMJjm7en4uYruw3XKA25bJmVZQv+AGuX2Vng==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1l4stuz0vr7gs7pqwjrmezam44702jp2vmqaqyxw0l0r42kf9updq4dfhrw
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlMitMRG42WmpxTmRIVGJQ
            Znh1dHlGY0dRb0Y3QmNqdm11WE56cXNHejBZClJpZUtFcnR1V2didUE3dEs3K3kw
            SWFaNXFVMGhjYWVmR1Z2Z3U2WW9hREUKLS0tIGorQldaclFBc1BQYzMyb3NEZ21l
            dVAzQW9CRkJxSWJ2T09FN1U1L0VHRk0K447wEibYlAzZdgo7ojMiwsOSXxqELhU2
            atPIjukkDTZHA71zkHDbRqSoUg4cKXHv5MSSaDzD6krs+anU49dlEQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k2y0vm4tmf88vg6zfed8q8zv544g4u0l5ry4kmm4hmzslvj5vdxskhat2n
    lastmodified: "2026-05-12T12:22:48Z"
    mac: ENC[AES256_GCM,data:Jc2aclU3Q9M7rsIO/Ww9R+YlX8+c3Xvhe2wKGl8o+O9TwL+MUW7h2Vk968RBBmktRCz62RopF4d36QZK8uQIc8kYdXuQn+papxejxp7N7rTSNVGovNCI9RCSwg0R3MEoEpQQkm8NPyI+apSVX+2H0Qx8tQuxPKWSBuvpaijOQlE=,iv:D+3xvpnhclcEV0FWhnZ9dqkXazh2BqYbornzpumeOyI=,tag:Ex68R7pqSjTDVj/z7p+OyA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
