keys: # cat /etc/ssh/ssh_host_ed25519_key.pub | ssh-to-age
  - &chn age19ax6vm3pv8rph5tq3mmehd9sy9jk823tw8svsd790r0lkslycquqvlwz9m
  - &pc age1ffvr5pqd2lfj24e3fh53s92z6h76fda3du4y4k6r3yjumdwvpfgqzj033a
  - &vps4 age1yvrl4y0r6yzcxzzkgfwshlrtsjt8uuya6rfwks09pnft7esfcyvqmrtm5q
  - &vps6 age164tyqklwhdm57tfm5u863mdt2xrzrrzac4py8a0j9y6kzqcjy9zsp073t6
  - &vps7 age137x7csalutwvfygvvzpemlsywvdxj3j4z93a50z2sjx03w6zau8q3r5902
  - &surface age1ck5vzs0xqx0jplmuksrkh45xwmkm2t05m2wyq5k2w2mnkmn79fxs6tvl3l
  - &nas age19lhcwk37jmvn6z0v4dpdfh0k4u23f76twdjknc0p7atktf37rd7s4t4wj3
  - &xmupc1 age1hnarptkze0ujpp05dqr8uma04cxg9zqcx68qgpks5uf5l6rpk5gqhh8wxg
  - &xmupc2 age1l4stuz0vr7gs7pqwjrmezam44702jp2vmqaqyxw0l0r42kf9updq4dfhrw
  - &pi3b age1yjgswvexp0x0de0sw4u6hamruzeluxccmx2enxazl6pwhhsr2s9qlxdemq
  - &pcvm age1jmu4jym0e0xkq5shx2g7ef4xzre94vaxy2n4fcn0kp94dtlupdxqkzyyp7
  - &srv1 age1ffvr5pqd2lfj24e3fh53s92z6h76fda3du4y4k6r3yjumdwvpfgqzj033a
creation_rules:
  - path_regex: devices/pc/.*$
    key_groups:
    - age:
      - *chn
      - *pc
  - path_regex: devices/vps4/.*$
    key_groups:
    - age:
      - *chn
      - *vps4
  - path_regex: devices/vps6/.*$
    key_groups:
    - age:
      - *chn
      - *vps6
  - path_regex: devices/vps7/.*$
    key_groups:
    - age:
      - *chn
      - *vps7
  - path_regex: devices/nas/.*$
    key_groups:
    - age:
      - *chn
      - *nas
  - path_regex: devices/surface/.*$
    key_groups:
    - age:
      - *chn
      - *surface
  - path_regex: devices/xmupc1/.*$
    key_groups:
    - age:
      - *chn
      - *xmupc1
  - path_regex: devices/xmupc2/.*$
    key_groups:
    - age:
      - *chn
      - *xmupc2
  - path_regex: devices/pi3b/.*$
    key_groups:
    - age:
      - *chn
      - *pi3b
  - path_regex: devices/pcvm/.*$
    key_groups:
    - age:
      - *chn
      - *pcvm
  - path_regex: devices/srv1/.*$
    key_groups:
    - age:
      - *chn
      - *srv1
