slurm:
    munge: ENC[AES256_GCM,data:T1urx6Rd8TBe+vWBOHD3Ef8QRq5MLWeeiEwqeyJOaVb/tByQ8W+2fXLmhLylUDaREDYF/egGMZfeXfCfSABX6vAACmUTSh19hKS/aWcHtuTcARki+pffZPJnbGo/s/AksyGoObdRkwqdlWyKlB3bS9EB3E2kP0uE5GOwntIEJ54=,iv:JqheugdR/RFzXiMJjcP4dQcC6qiJg5bTx+OxkaH6i+E=,tag:jt9cuP5DMdLTAzPCMDk4gQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IGFUbWd4ZyBBLzkzUE1V
            aVFObnFyaUZiNTVVWnZLdDljUW1KOGVGOTFISElkS2t1OXRnNApOVWRsNHNoR0o5
            MkdZSHM4RFR3MExJNmk5N1pnNUI3Y09TeW02LytNdDM4Ci0tLSBZL0E5ZGEzV1JL
            b3VJK0dFSTBEVUNvMFB2RXhjUlVFbmE0aTVidjkxdDRvCrDlkzdF0kTvz4i7kX99
            uD/cF0wAyIlPb7t/cpVKMSDBppH62XtAX6OXcmNIXZKDA/a+UKWEGMXtq1WMF99s
            X3o=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qtkjcn7umxt8j9zvrmnu7r6rgvl69c2u2zv8ufut4de2ealk2axvj9k0f03
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvN1E2dWpDcGhMR0RQenUr
            Q2hPaE8xSDJQWjRoc1lkbDh6bWowMnFQWlVFCm56M0ZJKzVqMXhGMlloaVJhb3B0
            Y01vTXgxZ0tjY1NBS0MwU0tDSU55aVkKLS0tIDAxU0hXOWhEd2g1S09SdzhHWm5r
            dFkvNkxuWkRvMWlyb2ZNMkRGRzVRT2MK1mG/VEVIOvCNS+1l0U+/nrKo0nEXxwdM
            tx56vShCam4jYNEzruw7WZi6318BsGCnjEiQ1HMvSI5D802JFg5IUw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nzetyehldf3gl6pr6mu5d2cv387p8wjqn6wfpll7a3sl8us6n38s0ds633
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsRVd6ZDZ2aEs2eGpORW43
            b2tDWVZ5L1UwWVBGU3VqSUhRZUdxWDJLbG40Ck5xYWVTZWdaWE5SQVdWM1NyNmVH
            MFJLTnJqK2dQNXVZeXlucFA4TU5lZU0KLS0tIEZNeTV4Q09BQi9jYmh4SHdPVWhj
            c09palVWUXpXNGxGaG5sWWlPODNoUDQKFT2W7Hlx6oSJcqYyFMeyHpGDOZmHhZqO
            KnQBohPoU+341JjujWR64ZVfLpkobTG3bbbBFF0xUFcKT4goq0Y3CQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wj33xt8nj7rhnsenepsf6k3lmq5vk4wn84jwr55qy9cwu05xn5cspg3h7t
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdnRZM3ZxeEdhUUVubFRR
            aXhSNEoyZUJIejA5MWdJN2JTbzA4dUJxQ3dJClNGVEs0Z1dzZm1JV0F5TzVHVzFp
            RlpjRWVJaFk5QnI0OXJwT1hnblF0MncKLS0tIFlJWXJObVgxZG9Xb3E3TlcwM255
            MjFqcVZJQVQ3N3o4QW9vdG1VdThMNHMKVIT4YHNzcDh1oB09/lS13YXuut7r8EnG
            G0T14dwXfPYffAU6jVqfeNrhQs2t5wAcZNuHgWLL0N8oPD9Xlaqy3g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16e7ykphshal6qhwfvat698hl48s8yr0jvzh27ecdyfh5uk7t9u6s753jgy
    lastmodified: "2026-05-12T12:22:13Z"
    mac: ENC[AES256_GCM,data:VP+jMwfkPm9oHI8ngnXeNgRk60Da1BNBDGgIUM8EbJ81aBT+65wdayi4thAuQC72IiWcIQHbtLHzHbR6eWbh7rIMkAS+XB4q1T6tcb/nXnO7P6L6YuaUsHiiTIapDAJxV1x81CfJwk8hGhUQEPlnlXqBSjb+aXKa9rWyasXpx/8=,iv:HQK4D4+HnqoyCX9aFFHPBDVtDOvw8g7XiXB9dt6i/mY=,tag:obLlxhqqWmioaKrhBfyndQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
