keys: # cat /etc/ssh/ssh_host_ed25519_key.pub | ssh-to-age
  - &chn age19ax6vm3pv8rph5tq3mmehd9sy9jk823tw8svsd790r0lkslycquqvlwz9m
  - &pc age1ffvr5pqd2lfj24e3fh53s92z6h76fda3du4y4k6r3yjumdwvpfgqzj033a
  - &vps4 age1yvrl4y0r6yzcxzzkgfwshlrtsjt8uuya6rfwks09pnft7esfcyvqmrtm5q
  - &vps6 age164tyqklwhdm57tfm5u863mdt2xrzrrzac4py8a0j9y6kzqcjy9zsp073t6
  - &vps10 age1navuwp0q2dw28h6zrkv5mhjexkt72475c0rd9rel0x6xf5a205ns82qv6j
  - &nas age19lhcwk37jmvn6z0v4dpdfh0k4u23f76twdjknc0p7atktf37rd7s4t4wj3
  - &srv1-node0 age1nzetyehldf3gl6pr6mu5d2cv387p8wjqn6wfpll7a3sl8us6n38s0ds633
  - &srv1-node1 age1wj33xt8nj7rhnsenepsf6k3lmq5vk4wn84jwr55qy9cwu05xn5cspg3h7t
  - &srv1-node2 age16e7ykphshal6qhwfvat698hl48s8yr0jvzh27ecdyfh5uk7t9u6s753jgy
  - &srv2-node0 age1hnarptkze0ujpp05dqr8uma04cxg9zqcx68qgpks5uf5l6rpk5gqhh8wxg
  - &srv2-node1 age1l4stuz0vr7gs7pqwjrmezam44702jp2vmqaqyxw0l0r42kf9updq4dfhrw
  - &srv2-node2 age1k2y0vm4tmf88vg6zfed8q8zv544g4u0l5ry4kmm4hmzslvj5vdxskhat2n
  - &pe age10ud96nzj0wu6s3g89md939md4dyh9ynt9zgnxn0njqx79d9ydpessltcma
creation_rules:
  - path_regex: '^default\.yaml$'
    key_groups:
    - age: [ *chn, *pc, *vps4, *vps6, *vps10, *nas, *srv1-node0, *srv1-node1, *srv1-node2, *srv2-node0,
      *srv2-node1, *srv2-node2, *pe ]
  - path_regex: '^chn\.yaml$'
    key_groups:
    - age: [ *chn, *pc, *nas ]
  - path_regex: '^xray-server\.yaml$'
    key_groups:
    - age: [ *chn, *vps4, *vps6, *vps10, *nas ]
  - path_regex: '^devices/pc\.yaml$'
    key_groups: [{ age: [ *chn, *pc ] }]
  - path_regex: '^devices/vps4\.yaml$'
    key_groups: [{ age: [ *chn, *vps4 ] }]
  - path_regex: '^devices/vps6\.yaml$'
    key_groups: [{ age: [ *chn, *vps6 ] }]
  - path_regex: '^devices/vps10\.yaml$'
    key_groups: [{ age: [ *chn, *vps10 ] }]
  - path_regex: '^devices/nas\.yaml$'
    key_groups: [{ age: [ *chn, *nas ] }]
  - path_regex: '^devices/srv1/default\.yaml$'
    key_groups: [{ age: [ *chn, *srv1-node0, *srv1-node1, *srv1-node2 ] }]
  - path_regex: '^devices/srv1/node0\.yaml$'
    key_groups: [{ age: [ *chn, *srv1-node0 ] }]
  - path_regex: '^devices/srv1/node1\.yaml$'
    key_groups: [{ age: [ *chn, *srv1-node1 ] }]
  - path_regex: '^devices/srv1/node2\.yaml$'
    key_groups: [{ age: [ *chn, *srv1-node2 ] }]
  - path_regex: '^devices/srv2/default\.yaml$'
    key_groups: [{ age: [ *chn, *srv2-node0, *srv2-node1, *srv2-node2 ] }]
  - path_regex: '^devices/srv2/node0\.yaml$'
    key_groups: [{ age: [ *chn, *srv2-node0 ] }]
  - path_regex: '^devices/srv2/node1\.yaml$'
    key_groups: [{ age: [ *chn, *srv2-node1 ] }]
  - path_regex: '^devices/srv2/node2\.yaml$'
    key_groups: [{ age: [ *chn, *srv2-node2 ] }]
  - path_regex: '^devices/pe\.yaml$'
    key_groups: [{ age: [ *chn, *pe ] }]
