providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: env/OCTODNS_CONFIG
    enforce_order: false
  cloudflare:
    class: octodns_cloudflare.CloudflareProvider
    token: env/CLOUDFLARE_TOKEN
    pagerules: false
zones:
  '*':
    sources:
      - config
    targets:
      - cloudflare
