providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: env/OCTODNS_CONFIG
    enforce_order: false
  cloudflare:
    class: octodns_cloudflare.CloudflareProvider
    token: env/CLOUDFLARE_TOKEN
    pagerules: false
processors:
  ignore_nas:
    class: octodns.processor.filter.NameRejectlistFilter
    rejectlist:
      - /^nas$/
zones:
  '*':
    sources:
      - config
    targets:
      - cloudflare
    processors:
      - ignore_nas
