#!/bin/sh /etc/rc.common
# Copyright (C) 2010 Jo-Philipp Wich

START=99
STOP=01

start() {
  ipset create xmunet hash:net
  ipset add xmunet 218.193.58.125
  ipset add xmunet 210.34.0.35
  ipset add xmunet 121.192.191.10
  ipset add xmunet 10.24.84.31
  ipset add xmunet 59.77.0.143
  ipset add xmunet 59.77.36.248
  ipset add xmunet 172.27.124.24
  ipset add xmunet 59.77.36.156
  ipset add xmunet 59.77.36.223
  ipset add xmunet 210.34.0.84
  ipset add xmunet 218.193.50.157
  ipset add xmunet 210.34.16.60
  ipset add xmunet 10.26.14.70
  ipset add xmunet 10.26.14.56
  ipset add xmunet 210.34.16.20
  ipset add xmunet 59.77.36.250
  iptables -t mangle -A PREROUTING ! -s 192.168.1.2 -m set --match-set xmunet dst -j MARK --set-mark 1/1
  ip route add unicast 0.0.0.0/0 via 192.168.1.2 dev br-lan table 100
  ip rule add fwmark 1/1 table 100
}

stop() {
  iptables -t mangle -D PREROUTING ! -s 192.168.1.2 -m set --match-set xmunet dst -j MARK --set-mark 1/1 -w
  # somehow -w does not work
  sleep 1
  ip rule del fwmark 1/1 table 100
  ip route del table 100
  ipset flush xmunet
  ipset destroy xmunet
}
